apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-exporter
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: prometheus-exporter
  endpoints:
    - port: http
      path: /metrics
  namespaceSelector:
    matchNames:
      - default
