apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics-script
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statistics-script
  template:
    metadata:
      labels:
        app: statistics-script
    spec:
      containers:
        - name: statistics-script
          image: statistics-script:latest
          imagePullPolicy: Never
          volumeMounts:
            - name: data-volume
              mountPath: /data
      volumes:
        - name: data-volume
          emptyDir: {}
